apiVersion: v2
name: bird-app
description: A Helm chart for the Bird Application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: bird
    version: 0.1.0
    condition: bird.enabled
  - name: birdimage
    version: 0.1.0
    condition: birdimage.enabled