global:
  namespace: birdapp
  ingress:
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/tags: Environment=dev,Team=test

bird:
  enabled: true
  name: bird
  service:
    type: ClusterIP
    port: 4201
  ingress:
    enabled: true
    className: "alb"
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /bird
            pathType: Prefix
    tls: []

birdimage:
  enabled: true
  name: birdimage
  service:
    type: ClusterIP
    port: 4200
  ingress:
    enabled: true
    className: "alb"
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /birdimage
            pathType: Prefix
    tls: []