global:
  namespace: birdapp
  ingress:
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: 'instance'
      alb.ingress.kubernetes.io/group.name: bird-alb

bird:
  enabled: true
  name: bird
  service:
    type: NodePort
    port: 4201
  ingress:
    enabled: true
    className: "alb"
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
    tls: []

birdimage:
  enabled: true
  name: birdimage
  service:
    type: NodePort
    port: 4200
  ingress:
    enabled: true
    className: "alb"
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix
    tls: []